Meteor.subscribe('channels');
Meteor.subscribe('items');
Meteor.subscribe('marketItems');
Meteor.subscribe('listings');
Meteor.subscribe('transactions');
Meteor.subscribe('realtimetrade');
Meteor.subscribe('userPresence');
Meteor.subscribe('userData');
Meteor.subscribe('genericItems');
